### ISSUE TITLE
Query about QEMU-RISCV

### ISSUE THREAD

**Issue by TR174** [lowRISC/qemu#2]
Hi,
Can you please help me on how to integrate qemu-riscv with RTL? Thanks.

**Comment by jrrk** [comment]
Dear Tashfia,
  In theory you could use Verilator to convert lowRISC peripherals to C++ modules that can interface with QEMU. Usually it’s not done this way though because it would have too big an impact on the performance of the simulation. The more usual way is to write or adapt a behavioural model of each peripheral. However this has not been done by us since we are primarily developing hardware rather than software, and in this case a behavioural model is insufficiently accurate.

Regards,
Jonathan
