### ISSUE TITLE
Sample vmem or hsjon input files for otptool

### ISSUE THREAD

**Issue by stefanberger** [lowRISC/qemu#68]
I was looking around for a sample vmem file to pass to the otptool but couldn't find one that would work. Do you have an example input file somewhere? I tried this one here but it's not in the expected format:

https://github.com/lowRISC/opentitan/blob/master/sw/host/opentitanlib/src/otp/testdata/output.vmem

Also I could not find a hjson file I could pass as input.

**Comment by loiclefort** [comment]
Since you are using Darjeeling, you need to use OpenTitan `integrated_dev` branch.
Using this branch, you can build OTP vmem files using bazel, for example for an OTP with a lifecycle in "prod" state:
```
./bazelisk.sh build //hw/ip/otp_ctrl/data:img_prod
```
(result in `bazel-out/k8-fastbuild/bin/hw/ip/otp_ctrl/data/img_prod.24.vmem`)
Other images can be generated too, use `./bazelisk.sh query //hw/ip/otp_ctrl/data:*` for other bazel `img_*` targets.

hjson file for Darjeeling OTP is there: [otp_ctrl_mmap.hjson](https://github.com/lowRISC/opentitan/blob/integrated_dev/hw/ip/otp_ctrl/data/otp_ctrl_mmap.hjson)
